import os

path = "c:/data/"
FIPS = "0000"
latex_file = open(f"{path}Profile_{FIPS}.tex", "w+")

latex_file.write("\\documentclass{article} \n ")
latex_file.write(" \n ")
latex_file.write("\\pagestyle{empty} \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage[margin=1in]{geometry} % Fix margins  \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage{fancyhdr} % Special Headers & Footers  \n ")
latex_file.write(" 	\\pagestyle{fancy}  \n ")
latex_file.write(" 	\\fancyhead[C]{\\LARGE{\\textcolor{arcindigo}{\\textbf{Demographic Profile: Fulton County}}}}   \n ")
latex_file.write(" 	\\fancyfoot[R]{\\href{http://www.atlantaregional.org}{\\includegraphics[height = .25in]{ARCMarkGold.pdf}}} % Put logo in footer and have it be a clickable link \n ")
latex_file.write(" 	\\fancyfoot[C]{}  \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage[hidelinks]{hyperref} % Allows you to make links, such as outside URLs. The hidelinks option suppresses any boxes. \n ")
latex_file.write("\\usepackage{bookmark} % Allows for bookmarks in the PDF \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage{graphicx}	% Enables insertion of outside images into doc  \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage{wheelchart} % Need for pie graphs \n ")
latex_file.write("\\usepackage{pgfplots} % Need for bar graphs \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage{fontspec} % Enables TrueType fonts  \n ")
latex_file.write(" 	\\setmainfont{Din-Pro} % Name your font \n ")
latex_file.write(" \n ")
latex_file.write("\\usepackage[table]{xcolor} % Enables colors and color definition  \n ")
latex_file.write(" 	\\definecolor{arcgold}{RGB}{255,184,53}  \n ")
latex_file.write(" 	\\definecolor{arcgray}{RGB}{126,125,127}  \n ")
latex_file.write(" 	\\definecolor{arcred}{RGB}{238,87,93}  \n ")
latex_file.write(" 	\\definecolor{arcpurple}{RGB}{99,110,160}  \n ")
latex_file.write(" 	\\definecolor{arcindigo}{RGB}{18,112,179}  \n ")
latex_file.write(" 	\\definecolor{arcblue}{RGB}{66,173,211}  \n ")
latex_file.write(" 	\\definecolor{arcteal}{RGB}{26,175,166}  \n ")
latex_file.write(" 	\\definecolor{arcforest}{RGB}{103,133,57}  \n ")
latex_file.write(" 	\\definecolor{arcgreen}{RGB}{152,174,62}  \n ")
latex_file.write(" \n ")
latex_file.write(" \n ")
latex_file.write("\\begin{document} \n ")
latex_file.write(" \n ")
latex_file.write("\\section*{\\textcolor{arcindigo}{Race and Ethnicity}} \n ")
latex_file.write("\\addcontentsline{toc}{section}{Race and Ethnicity} % Optional (if you want a bookmark) \n ")
latex_file.write(" \n ")
latex_file.write("\\rowcolors{2}{arcgray!25}{white} % alternate gray and white rows in table \n ")
latex_file.write("\\def\\arraystretch{1.25} % give some extra vspace in table \n ")
latex_file.write(" \n ")
latex_file.write("\\begin{tabular}{ p{4in} r r } \n ")
latex_file.write(" \n ")
latex_file.write("& \\textbf{Count} & \\textbf{Percent} \\\\ \n ")
latex_file.write("Total Population & 1,076,561 & 100\\% \\\\  \n ")
latex_file.write("Non-Hispanic White & 396,329 & 37\\% \\\\ \n ")
latex_file.write("Non-Hispanic Black or African American & 453,703 & 42\\% \\\\ \n ")
latex_file.write("Non-Hispanic Asian & 83,505 & 8\\% \\\\ \n ")
latex_file.write("Non-Hispanic Other & 55,057 & 5\\% \\\\ \n ")
latex_file.write("Hispanic or Latino, All Races & 87,967 & 8\\%\\\\ \n ")
latex_file.write(" \n ")
latex_file.write("\\end{tabular} \n ")
latex_file.write("\\rowcolors{1}{}{} % Reset table row shading to default \n ")
latex_file.write(" \n ")
latex_file.write(" \n ")
latex_file.write("\\section*{\\textcolor{arcindigo}{Educational Attainment}} \n ")
latex_file.write("\\addcontentsline{toc}{section}{Educational Attainment} % Optional (if you want a bookmark) \n ")
latex_file.write(" \n ")
latex_file.write("\\begin{tikzpicture} \n ")
latex_file.write("    \\wheelchart[ \n ")
latex_file.write("        pie, \n ")
latex_file.write("        radius={0}{3}, \n ")
latex_file.write("        slices style={fill=\\WClistcolors, draw=none}, \n ")
latex_file.write("        WClistcolors={arcred, arcblue, arcteal, arcgreen}, \n ")
latex_file.write("        value=\\WCvarA, \n ")
latex_file.write("        % Inside Slices: Show Percentages \n ")
latex_file.write("        wheel data=\\WCperc, \n ")
latex_file.write("        wheel data style={black, font=\\small}, \n ")
latex_file.write("        % Legend: Show Labels (e.g., Less than HS) \n ")
latex_file.write("        legend row={\\tikz\\fill[\\WClistcolors] (0,0) rectangle (0.2,0.2); & \\WCvarB}, \n ")
latex_file.write("        legend={ \n ")
latex_file.write("            \\node[right] at (4,0) { \n ")
latex_file.write("                \\begin{tabular}{ll} \n ")
latex_file.write("                    \\WClegend \n ")
latex_file.write("                \\end{tabular} \n ")
latex_file.write("            }; \n ")
latex_file.write("        }, \n ")
latex_file.write("        % Disable the default label search \n ")
latex_file.write("        data={}  \n ")
latex_file.write("    ]{ \n ")
latex_file.write("        6/Less than HS, \n ")
latex_file.write("        15/HS or GED, \n ")
latex_file.write("        20/Some College, \n ")
latex_file.write("        58/BA or Higher \n ")
latex_file.write("    } \n ")
latex_file.write("\\end{tikzpicture} \n ")
latex_file.write(" \n ")
latex_file.write("\\section*{\\textcolor{arcindigo}{Housing Cost Burdened Households}} \n ")
latex_file.write("\\addcontentsline{toc}{section}{Housing Cost Burdened Households} % Optional (if you want a bookmark) \n ")
latex_file.write(" \n ")
latex_file.write("\\begin{tikzpicture} \n ")
latex_file.write("	\\begin{axis}[ytick style={draw=none}, xtick style={draw=none}, \n ")
latex_file.write("	axis lines*=left, \n ")
latex_file.write("	xbar, \n ")
latex_file.write("	bar width=25pt, % Adjust width as needed \n ")
latex_file.write("	enlarge x limits=0, \n ")
latex_file.write("	enlarge y limits=0.6, % Adjust spacing as needed \n ")
latex_file.write("	legend style={at={(0.5,-0.1)}, % Put legend below graph \n ")
latex_file.write("	draw=none, % suppress box around legend itself \n ")
latex_file.write("	anchor=north,legend columns=-1, % legend placement and orientation \n ")
latex_file.write("	/tikz/every even column/.append style={column sep=20pt} \n ")
latex_file.write("	}, \n ")
latex_file.write("		symbolic y coords={Georgia, Fulton County}, \n ")
latex_file.write("	xmin = 0, \n ")
latex_file.write("	xmax = 100, \n ")
latex_file.write("	ytick=data, \n ")
latex_file.write("	nodes near coords={\\pgfmathprintnumber{\\pgfplotspointmeta}\\%}, \n ")
latex_file.write("	nodes near coords align={horizontal}, \n ")
latex_file.write("	y tick label style={rotate=0,anchor=east}, \n ")
latex_file.write("	x tick label style={/pgf/number format/fixed, /pgf/number format/assume math mode},  \n ")
latex_file.write("	nodes near coords style={/pgf/number format/assume math mode} \n ")
latex_file.write("	] \n ")
latex_file.write("	\\addplot[draw=none,fill=arcpurple] coordinates { \n ")
latex_file.write("		(21,Georgia) (23,Fulton County)   \n ")
latex_file.write("	}; \n ")
latex_file.write("	\\addplot[draw=none,fill=arcred] coordinates { \n ")
latex_file.write("		(52,Georgia) (51,Fulton County)   \n ")
latex_file.write("		}; \n ")
latex_file.write(" \n ")
latex_file.write("	\\pgfplotsset{ \n ")
latex_file.write("		legend image code/.code={ \n ")
latex_file.write("			\\draw [draw=none, #1] (0cm,-0.1cm) rectangle (0.6cm,0.1cm); % draw=none suppresses box around legend icons \n ")
latex_file.write("		}, \n ")
latex_file.write("	} \n ")
latex_file.write("	\\legend{Owners, Renters} \n ")
latex_file.write(" \n ")
latex_file.write("	\\end{axis} \n ")
latex_file.write("\\end{tikzpicture} \n ")
latex_file.write(" \n ")
latex_file.write("\\end{document} \n ")
latex_file.write(" \n ")
latex_file.write(" \n ")


latex_file.close()

os.system(f'lualatex "c:/data/Profile_{FIPS}.tex"')
